# Generated by Django 4.2.3 on 2023-10-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_product_user_alter_image_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_url',
            field=models.ImageField(upload_to='media/img/'),
        ),
    ]
